name: Border0
description: SSH access to your GitHub Actions VM using Border0
author: Border0
branding:
  icon: terminal
  color: orange
inputs:
  token:
    description: 'API token'
    required: true
  slack-webhook-url:
    description: 'Sack webhook URL'
    required: false
    default: ''
  background-mode:
    description: 'Run in the background'
    required: false
    default: 'false'
  clean-up-mode:
    description: 'Perform cleanup only'
    required: false
    default: 'false'
  wait-for:
    description: 'Wait for n minutes before cleaning up'
    required: false
    default: '15'

runs:
  using: 'node16'
  main: 'index.js'

